### ISSUE TITLE
plot_circuit shows beamer overlay and trims too much

### ISSUE THREAD

**Issue by eddieschoute** [QISKit/qiskit-sdk-py#335]
When plotting a small circuit the output image displays the TeX beamer overlay and also trims too much of the image on the sides.

## Expected Behavior
When plotting a circuit I expect the circuit to be shown completely and to also not have any additional clutter but the circuit.

## Current Behavior
When plotting by the following:
```py
def test_unroller():
    qasm_text = """
    OPENQASM 2.0;
    include "qelib1.inc";

    // add two 8-bit numbers by calling the 4-bit ripple-carry adder
    // carry bit on output lives in carry[0]
    qreg q[2];
    creg c[1];
    h q[0];
    cx q[0], q[1];
    measure q[0] -> c[0];
    """
    qasm = Qasm(data=qasm_text).parse()
    circuit : QuantumCircuit = Unroller(qasm, CircuitBackend()).execute()
    plot_circuit(circuit)
```
the following image is displayed:
![sample_circuit](https://user-images.githubusercontent.com/25747714/37358076-7fe2692c-26c0-11e8-9e46-cc855e7b3a64.png)

Note the beamer overlay on the bottom right, and the bras being cut off on the left.

## Possible Solution
The trimming function is somehow trimming too much of the input image which is undesirable. The beamer overlay can be hidden with the appropriate beamer settings.

## Steps to Reproduce (for bugs)
Run the example code

## Context
I'm trying to use OpenQASM to make circuit plots. It would be nice if a stand-alone command-line tool was available, because I can see this being useful. However, it would need to support vector images, whereas it currently converts to pngs. E.g. output to pdf or eps.

## Your Environment
* Version used: qiskit 0.4.10
* Environment name and version (e.g. Python 3.6.1): 3.6.4
* Operating System and version: macOS 10.13

**Comment by eddieschoute** [comment]
In an effort to display a Hadamard as an "H" gate I changed the code to
```py
def test_unroller():
    qasm_text = """
    OPENQASM 2.0;
    include "qelib1.inc";

    // add two 8-bit numbers by calling the 4-bit ripple-carry adder
    // carry bit on output lives in carry[0]
    qreg q[2];
    creg c[1];
    h q[0];
    cx q[0], q[1];
    measure q[0] -> c[0];
    """
    qasm = Qasm(data=qasm_text).parse()
    circuit : QuantumCircuit = Unroller(qasm, CircuitBackend(
        basis=["u1","u2","u3","id","cx","x","y","z","h","s","t","rx","ry","rz"])).execute()
    im = plot_circuit(circuit)
    pass
```
which somehow resolved the above two issues and produces a decent image. I am not sure why.
I'd still like a way to get obtain a vector image though.

**Comment by ajavadia** [comment]
With the latest release you should be able to get Hadamard gate without manually specifying an unroller.

I have also noticed the over-trimming for small circuits, which should be fixed.

The OpenQASM->svg tool you are asking for has been suggested by a user in #311.

**Comment by eddieschoute** [comment]
> The OpenQASM->svg tool you are asking for has been suggested by a user in #311.

It seems that would be a standalone tool. I figure that it would be relatively straightforward to wrap the `plot_circuit` functionality in [a script](https://docs.python.org/3/distutils/setupscript.html#installing-scripts) that can be added to the `qiskit` distribution. At least until a pure python alternative is implemented (then it should be fairly straightforward to switch out the script backend).

**Comment by nelimeee** [comment]
I wrote a quick function to correct (in a dirty way) some of the drawbacks of `latex_drawer` (used internally by `plot_circuit`). The function just change the LaTeX code produced:

```py
def fix_latex_compilation(latex_code:str) -> str :
    """Fix the problem of LaTeX code generation of qiskit.tools.visualization.latex_drawer.

    The two issues fixed are:
        1) Problem of font finding, solved by the line "\pdfmapfile{+sansmathaccent.map}".
        2) The navigation symbols of Beamer were appearing on the image, solved by the line
           "\beamertemplatenavigationsymbolsempty".
        3) Problem of size

    Input:
        latex_code (str): a string containing the LaTeX code produced by latex_drawer.

    Output:
        (str) the corrected LaTeX code (i.e. compilable on my machine).
    """

    # First replace the size of the beamer poster
    match = re.search(r"img_depth = (\d+), img_width = (\d+)", latex_code);
    depth, width = match.group(1), match.group(2)
    latex_code = re.sub(r"usepackage\[size=custom,width=\d+,height=\d+\]",
                        r"usepackage[size=custom,width=" + str(int(1.5*int(depth))) + r",height=" + str(int(1.5*int(width))) + r"]",
                        latex_code)
```
You need an `import re` in your Python file, and I think the problem of size is not really fixed by the function.

**Comment by ajavadia** [comment]
@nelimeee thanks. I will try to fix a few things in the latex code. But it seems like the code you posted is truncated? I don't see the lines that the comment refers to for font and beamer.

**Comment by nelimeee** [comment]
I edited my comment with the full function! Thanks =)
